#!/usr/bin/env node
// invariants-catalog — emit a human-readable Markdown index of the
// orchestrator's invariant catalog.
//
// Sister to the interface-side `scripts/scenarios-catalog.mjs` which
// auto-generates `scenarios/SCENARIOS.md`. Same shape, different
// data source: there it's `*.scenario.mjs` files; here it's the
// in-process `INVARIANTS` array exported by `orchestrator/invariants.mjs`.
//
// Sister also to `scripts/scenarios-by-layer.mjs` which prints the
// same data to stdout. The by-layer script is for ad-hoc CLI use;
// this script writes a *committed* catalog so the index is browsable
// on GitHub without running anything, and so doc-rot is detectable
// (a sister smoke test diffs the regenerated output against the
// committed file).
//
// Output: `orchestrator/INVARIANTS.md` — header + per-layer summary
// table + one detail table per layer (# / name / description).
//
// Run via:  npm run invariants:catalog
//
// Per Phase 7 slice 4d-invariants-catalog.

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { INVARIANTS } from '../orchestrator/invariants.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = join(__dirname, '..', 'orchestrator', 'INVARIANTS.md');

const REQUIRED_FIELDS = ['name', 'description', 'layer'];

function escapePipes(s) {
    // Markdown table cells: `|` ends the cell. Escape with `\|` so
    // descriptions that legitimately contain pipes don't break the
    // table layout.
    return String(s ?? '').replace(/\|/g, '\\|');
}

for (const inv of INVARIANTS) {
    for (const field of REQUIRED_FIELDS) {
        if (!inv[field]) {
            throw new Error(`invariant "${inv.name ?? '<unnamed>'}" missing required field "${field}"`);
        }
    }
}

const byLayer = new Map();
for (const inv of INVARIANTS) {
    if (!byLayer.has(inv.layer)) byLayer.set(inv.layer, []);
    byLayer.get(inv.layer).push(inv);
}

const layers = [...byLayer.keys()].sort();
const total = INVARIANTS.length;

const lines = [
    '# Cross-layer invariants — coverage index',
    '',
    '_Auto-generated by `scripts/invariants-catalog.mjs`. Do not edit by hand;',
    'run `npm run invariants:catalog` from `auto-qa/harness/` to regenerate',
    'after adding or changing an invariant._',
    '',
    'Each row is a single invariant in the orchestrator\'s catalog. The',
    '`scenario-runner.mjs` runs them sequentially against the live stack;',
    'this doc is the human-readable index of WHAT the harness asserts and',
    'at WHICH layer.',
    '',
    `Total invariants: **${total}** across **${layers.length}** layers.`,
    '',
    '## Summary by layer',
    '',
    '| Layer | Count |',
    '|---|---|',
];

for (const layer of layers) {
    lines.push(`| \`${layer}\` | ${byLayer.get(layer).length} |`);
}

lines.push('');

for (const layer of layers) {
    const invs = byLayer.get(layer);
    lines.push(`## \`${layer}\` (${invs.length})`);
    lines.push('');
    lines.push('| #  | Name | Description |');
    lines.push('|----|------|-------------|');
    invs.forEach((inv, i) => {
        const id = String(i + 1).padStart(2, '0');
        lines.push(`| ${id} | \`${inv.name}\` | ${escapePipes(inv.description)} |`);
    });
    lines.push('');
}

writeFileSync(OUTPUT_FILE, lines.join('\n'));
console.log(`✓ Wrote ${OUTPUT_FILE} (${total} invariants across ${layers.length} layers)`);
